image: node:10.15.3

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - test -e package.json && npm run build
  - QLBoard generate

pages:
  script:
    - QLBoard generate
  artifacts:
    paths:
      - public
  only:
    - master
