image: node:16.1.0

cache:
  paths:
    - node_modules/

before_script:
  - test -e package.json && npm install
  - QLBoard generate

pages:
  script:
    - QLBoard generate
  artifacts:
    paths:
      - public
  only:
    - master
